---
version: '3.8'
x-common:
  database: &db-environment
    POSTGRES_DB: crayon_cloud #crayon_kali,crayon_dan,crayon_sam,crayon_nik,crayon_shared
    POSTGRES_USER: &pg-user crayon
    POSTGRES_PASSWORD: craycray123
    TZ: Australia/Melbourne
    POSTGRES_LOCATION: &db-location "~/db:/var/lib/postgresql/data"
  backup: &backup-environment
    POSTGRES_DB: crayon_kali,crayon_dan,crayon_sam,crayon_nik,crayon_shared
    POSTGRES_USER: &pg-user crayon
    POSTGRES_PASSWORD: spiny-settee-hullo
    SCHEDULE: "@daily"
    BACKUP_KEEP_DAYS: 30
    BACKUP_KEEP_WEEKS: 4
    BACKUP_KEEP_MONTHS: 12
    BACKUP_LOCATION: &bk-location "~/backups:/backups"
#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. 
# Please only make modifications
# below if you understand what you are doing.
#
services:
  postgres:
    container_name: resolve_pgsql
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      <<: [*db-environment]
    volumes:
      - *db-location
    healthcheck:
      test: ["CMD", "pg_isready", "-U", *pg-user]
      interval: 10s
      timeout: 5s
      retries: 5
  pgbackups:
    container_name: resolve_pgbackup
    image: prodrigestivill/postgres-backup-local:13
    restart: always
    volumes:
      - *bk-location
    depends_on:
      - postgres
    environment:
      <<: [*backup-environment]
      POSTGRES_HOST: postgres
      POSTGRES_EXTRA_OPTS: --blobs --format=custom --quote-all-identifiers
      BACKUP_SUFFIX: .backup
      HEALTHCHECK_PORT: 8080
    healthcheck:
      interval: 30s
